### ISSUE TITLE
"No such file or directory" when additional binaries are not in the default path

### ISSUE THREAD

**Issue by St333p** [RGB-WG/rgb-node#118]
When additional binaries (`stashd`, `fungibled`) are not in the default path (`/usr/local/bin` on linux) and the correct path is not specified with `-b`, `rgbd` panics with a generic error ("No such file or directory").

### Action points
- adding the missing filename to the error message would help troubleshooting: in general this error is not very informative
- should `rgbd` also search for binaries in `$PATH`?
- should `rgbd` have as default the path where `rgbd` binary is, and not an hardcoded one?

**Comment by dr-orlovsky** [comment]
With the next version I will be upgrading RGB Node to the same binary mechanism as in LNP Node:

https://github.com/LNP-BP/lnp-node/blob/master/src/lnpd/runtime.rs#L533-L559

It seems that it addresses all facts from the issue apart from using `$PATH` (not sure whether we should do this since it may have different version of the binaries which would not be compatible with the main daemon)

**Comment by St333p** [comment]
About `$PATH` you're right, I didn't consider that.

The solution used in LNP-node works pretty well, yes.
