### ISSUE TITLE
PstgreSQL storage engine for cache data

### ISSUE THREAD

**Issue by dr-orlovsky** [RGB-WG/rgb-node#59]

**Comment by rajarshimaitra** [comment]
Leaving this comment after initial trial of trying to implement Postgress over the Sqlite API.

It turns out `diesel` is not designed for flexible switching between database backends. Though the `PglConnection` and `SqlConnection` uses almost the same API, there's no straight forward way of holding them in a generic structure. 

Upon further research, I found this closed issue https://github.com/diesel-rs/diesel/issues/882, which describes the same problem. Which ultimately concludes that it's not possible. And diesel recommends using separate function calls for each back end.

The initial motivation for using diesel was for this compatibility. But seeing it out of option I think we need to go for explicite calling in our cache. The naive way to do it would be to create another `pgl` module replicating everything in `sql` module but with `PglConnection` in places of `SqlConnection`. This also requires duplicating functions in `cache/model.rs` and `data/assets.rs`. Which clearly looks very dirty to me.

Putting up this comment for community members to opine on whats would a more intelligent way to integrate Postgress.

The Sqlite implementation can be found here https://github.com/LNP-BP/rgb-node/blob/master/src/contracts/fungible/cache/sql.rs for reference.
